# Generated by Django 5.1.4 on 2024-12-07 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OtpCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.PositiveIntegerField(verbose_name='code')),
                ('expired_date', models.DateTimeField(verbose_name='expired date')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='otpuser', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
    ]
