# Generated by Django 5.1.4 on 2024-12-07 09:50

import account.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_passwordresettoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(max_length=11, unique=True, validators=[account.validators.MobileValidator()], verbose_name='شماره تلفن'),
        ),
    ]
