# Generated by Django 5.1.4 on 2025-01-01 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آپدیت')),
                ('title', models.CharField(max_length=300, verbose_name='نام برند')),
                ('slug', models.SlugField(blank=True, max_length=350, unique=True, verbose_name='اسلاگ')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Color',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='نام رنگ')),
            ],
        ),
        migrations.CreateModel(
            name='ProductFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os', models.CharField(max_length=300, verbose_name='سیستم عامل')),
                ('model', models.CharField(max_length=350, verbose_name='مدل گوشی')),
                ('size', models.CharField(max_length=350, verbose_name='سایز صفحه نمایش(اینچ)')),
                ('weight', models.CharField(max_length=150, verbose_name='وزن')),
                ('number_sim', models.SmallIntegerField(default=2, verbose_name='تعداد سیم کارت')),
                ('internal_memory', models.CharField(max_length=30, verbose_name='حافظه داخلی')),
                ('ram', models.CharField(max_length=20, verbose_name='مقدار RAM')),
                ('camera', models.CharField(max_length=50, verbose_name='کیفیت دوربین(مگاپیکسل)')),
            ],
        ),
        migrations.CreateModel(
            name='CategoryProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آپدیت')),
                ('title', models.CharField(max_length=350, verbose_name='عنوان')),
                ('slug', models.SlugField(allow_unicode=True, max_length=100, unique=True, verbose_name='اسلاگ')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parent_category', to='product.categoryproduct', verbose_name='زیرمجموعه')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('update_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ آپدیت')),
                ('title', models.CharField(max_length=500, verbose_name='نام محصول')),
                ('slug', models.SlugField(allow_unicode=True, max_length=65, unique=True, verbose_name='اسلاگ')),
                ('image', models.ImageField(upload_to='product_images', verbose_name='تصویر محصول')),
                ('price', models.IntegerField(verbose_name='قیمت محصول')),
                ('discount', models.SmallIntegerField(blank=True, null=True, verbose_name='تخفیف محصول(بر حسب درصد)')),
                ('available', models.BooleanField(default=True, verbose_name='موجود')),
                ('in_stock', models.SmallIntegerField(default=0, verbose_name='تعداد موجود در انبار')),
                ('desc', models.TextField(verbose_name='توضیحات')),
                ('published', models.BooleanField(default=True, verbose_name='نمایش بده')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='brand', to='product.brand', verbose_name='برند')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_product', to='product.categoryproduct', verbose_name='دسته بندی')),
                ('color', models.ManyToManyField(related_name='colors', to='product.color', verbose_name='رنگ های محصول')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feature_product', to='product.productfeature', verbose_name='مشخصات محصول')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ImagesProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploads/images_products', verbose_name='عکس')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='product.product', verbose_name='محصول')),
            ],
        ),
        migrations.CreateModel(
            name='FavoriteProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuser', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fproduct', to='product.product', verbose_name='محصول')),
            ],
        ),
        migrations.CreateModel(
            name='CommentProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('body', models.TextField(verbose_name='متن دیدگاه')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='product.commentproduct', verbose_name='پاسخ')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_comment_product', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_comment', to='product.product', verbose_name='محصول')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
