# Generated by Django 5.1.4 on 2025-01-02 08:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_categoryproduct_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentproduct',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(5)], verbose_name='امتیاز به محصول'),
        ),
    ]
