# Generated by Django 5.1.4 on 2025-01-02 13:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_commentproduct_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentproduct',
            name='rating',
            field=models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='امتیاز به محصول'),
        ),
    ]
