# Generated by Django 5.1.4 on 2025-01-05 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BanerHomeSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('image', models.ImageField(upload_to='baner/', verbose_name='عکس بنر')),
                ('link', models.URLField(blank=True, null=True, verbose_name='لینک')),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('image', models.ImageField(upload_to='slider/', verbose_name='عکس اسلایدر')),
                ('link', models.URLField(blank=True, null=True, verbose_name='لینک')),
            ],
        ),
    ]
