# Generated by Django 5.1.4 on 2025-01-05 16:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('full_name', models.CharField(max_length=300, verbose_name='نام و نام خانوادگی')),
                ('phone_number', models.CharField(max_length=11, verbose_name='شماره همراه')),
                ('email', models.EmailField(max_length=150, verbose_name='ایمیل')),
                ('subject', models.CharField(max_length=350, verbose_name='موضوع پیام')),
                ('content', models.TextField(verbose_name='متن پیام')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FooterLinkBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
            ],
        ),
        migrations.CreateModel(
            name='FooterSite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_name', models.CharField(max_length=250, verbose_name='نام فروشگاه')),
                ('icon_shop', models.ImageField(upload_to='icon_shop/', verbose_name='آیکون فروشگاه')),
                ('about_shop', models.TextField(verbose_name='درباره فروشگاه')),
                ('about_me', models.TextField(verbose_name='متن صفحه درباره ما')),
                ('address', models.CharField(max_length=500, verbose_name='آدرس')),
                ('email', models.EmailField(max_length=400, verbose_name='ایمیل')),
                ('phone', models.CharField(max_length=11, verbose_name='شماره تلفن')),
                ('copy_right', models.CharField(max_length=500, verbose_name='متن کپی رایت')),
            ],
        ),
        migrations.CreateModel(
            name='SocialMediaShop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.URLField(blank=True, null=True, verbose_name='فیسبوک')),
                ('twitter', models.URLField(blank=True, null=True, verbose_name='توییتر')),
                ('linkedin', models.URLField(blank=True, null=True, verbose_name='لینکدین')),
                ('pinterest', models.URLField(blank=True, null=True, verbose_name='پینترست')),
                ('telegram', models.URLField(blank=True, null=True, verbose_name='تلگرام')),
                ('instagram', models.URLField(blank=True, null=True, verbose_name='اینستاگرام')),
            ],
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان')),
                ('url', models.URLField(max_length=500, verbose_name='لینک')),
                ('footer_link_box', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='admin_contact.footerlinkbox', verbose_name='دسته بندی')),
            ],
        ),
    ]
