# Generated by Django 5.1.4 on 2025-01-01 13:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='آیدی')),
                ('status', models.CharField(choices=[('pending', 'در انتظار پرداخت'), ('complete', 'پرداخت شده'), ('failed', 'پرداخت ناموفق')], default='pending', max_length=20, verbose_name='وضعیت سفارش')),
                ('total_price', models.IntegerField(default=0, verbose_name='قیمت کل سفارش')),
                ('payment_date', models.DateTimeField(blank=True, null=True, verbose_name='تاریخ پرداخت')),
                ('is_paid', models.BooleanField(default=False, verbose_name='پرداخت شده؟')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('email', models.EmailField(blank=True, max_length=150, null=True, verbose_name='ایمیل(اختیاری)')),
                ('phone_number', models.CharField(max_length=11, verbose_name='شماره تلفن')),
                ('state', models.CharField(max_length=100, verbose_name='استان')),
                ('city', models.CharField(max_length=100, verbose_name='شهر')),
                ('zip_code', models.CharField(max_length=20, verbose_name='کد پستی')),
                ('address', models.CharField(max_length=300, verbose_name='آدرس')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_order', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='قیمت محصول')),
                ('color', models.CharField(max_length=20, verbose_name='رنگ محصول')),
                ('quantity', models.SmallIntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_item', to='order.order', verbose_name='سفارش')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_item', to='product.product', verbose_name='محصول')),
            ],
        ),
    ]
